controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
  # Example route definition in routes.yaml
home:
  path: /
  controller: App\Controller\HomeController::index
